# tests/test_reflector.py
#
# Pytest tests for SleepCycleReflector internals.
# The LLM client is fully mocked — no network calls are made.
#
# Card ID quick reference:
#   Green 7  = 6    Green 3 = 2    Green 5 = 4    Green 1 = 0
#   Yellow 5 = 32
#   Black 11 = 52   Black 1 = 42
#   Pirate   = 56   Skull King = 62   Escape = 65
#   Tigress  = 61   Tigress as Escape (virtual) = 74

import pytest
from unittest.mock import MagicMock
from src.engine.physics import GamePhysics
from src.memory.rag_engine import StrategyMemory
from src.memory.reflector import SleepCycleReflector


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def mock_client():
    """LLMClient whose generate() always returns a parseable [RULE]: line."""
    client = MagicMock()
    client.generate.return_value = "[RULE]: test rule text generated by mock"
    return client


@pytest.fixture
def memory(tmp_path):
    """Isolated StrategyMemory using a temporary ChromaDB directory."""
    import chromadb
    m = StrategyMemory.__new__(StrategyMemory)
    m.physics = None
    chroma_path = str(tmp_path / "chroma")
    m.client = chromadb.PersistentClient(path=chroma_path)
    m.zero_collection     = m.client.get_or_create_collection("forced_zero_strategies")
    m.rational_collection = m.client.get_or_create_collection("rational_strategies")
    return m


@pytest.fixture
def reflector(mock_client, memory):
    """SleepCycleReflector with a mocked LLM client and isolated memory."""
    return SleepCycleReflector(client=mock_client, memory=memory)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _trick_plays_for(players_and_cards):
    """
    Build a 'plays' list in the format the reflector expects:
        ["P0 played [Green 7]", "P1 played [Escape]", ...]
    """
    return [f"P{pid} played {card}" for pid, card in players_and_cards]


# ---------------------------------------------------------------------------
# Tests: _group_by_round
# ---------------------------------------------------------------------------

def test_group_by_round_captures_bidding_hand_ids(reflector):
    """
    BIDDING events must populate starting_hand_ids[pid] for each player.
    The first BIDDING event seen for a given pid in a round fixes that
    player's starting hand IDs.
    """
    events = [
        {"round": 1, "phase": "BIDDING", "player": 0, "action_id": 3,
         "my_hand": [56, 65, 6]},
        {"round": 1, "phase": "BIDDING", "player": 1, "action_id": 2,
         "my_hand": [62, 32, 4]},
    ]
    rounds = reflector._group_by_round(events)
    assert rounds[1]["starting_hand_ids"][0] == [56, 65, 6]
    assert rounds[1]["starting_hand_ids"][1] == [62, 32, 4]


def test_group_by_round_captures_trick_actions(reflector):
    """
    PLAYING events followed by a trick_end event must produce a tricks
    entry whose 'actions' list contains (player_id, action_id) tuples in
    play order, and whose 'winner' matches the trick_end event.
    """
    events = [
        {"round": 1, "phase": "PLAYING", "player": 0, "action_id": 6,
         "card_text": "[Green 7]",  "my_hand": [6, 65]},
        {"round": 1, "phase": "PLAYING", "player": 1, "action_id": 65,
         "card_text": "[Escape]",   "my_hand": [65]},
        {"round": 1, "phase": "PLAYING", "player": 2, "action_id": 32,
         "card_text": "[Yellow 5]", "my_hand": [32]},
        {"round": 1, "phase": "PLAYING", "player": 3, "action_id": 56,
         "card_text": "[Pirate]",   "my_hand": [56]},
        {"event_type": "trick_end", "round": 1, "winner": 3, "bonus": 0},
    ]
    rounds = reflector._group_by_round(events)
    trick = rounds[1]["tricks"][0]
    assert trick["actions"] == [(0, 6), (1, 65), (2, 32), (3, 56)]
    assert trick["winner"] == 3


def test_group_by_round_starting_hands_text(reflector):
    """
    The first PLAYING event for a player populates starting_hands[pid]
    with translated card text strings (e.g. '[Green 7]').
    """
    events = [
        {"round": 1, "phase": "PLAYING", "player": 0, "action_id": 6,
         "card_text": "[Green 7]", "my_hand": [6]},
        {"event_type": "trick_end", "round": 1, "winner": 0, "bonus": 0},
    ]
    rounds = reflector._group_by_round(events)
    hand_text = rounds[1]["starting_hands"][0]
    # translate_card(6) → "[Green 7]"
    assert any("[Green 7]" in s for s in hand_text)


# ---------------------------------------------------------------------------
# Tests: _find_critical_trick_with_index
# ---------------------------------------------------------------------------

def test_find_critical_trick_with_index_over_bid(reflector):
    """
    For an over-bid (won > bid), the critical trick is the (bid+1)th win
    by pid — the one that pushed the player beyond their bid.
    bid=1, won=2 → critical is the 2nd win by P0 (index 2).
    """
    tricks = [
        {"winner": 0, "plays": ["P0 played [Green 5]"]},   # P0's 1st win (bid met)
        {"winner": 1, "plays": ["P1 played [Black 7]"]},   # P0 didn't win
        {"winner": 0, "plays": ["P0 played [Pirate]"]},    # P0's 2nd win → critical
    ]
    trick, idx = reflector._find_critical_trick_with_index(pid=0, bid=1, won=2, tricks=tricks)
    assert idx == 2
    assert trick is tricks[2]


def test_find_critical_trick_with_index_under_bid(reflector):
    """
    For an under-bid (won < bid), the critical trick is the LAST trick
    in which pid did NOT win.
    bid=2, won=1 → last miss is tricks[2] (P0 never won trick 3).
    """
    tricks = [
        {"winner": 0, "plays": ["P0 played [Black 14]"]},  # P0 wins
        {"winner": 1, "plays": ["P1 played [Skull King]"]},# P0 misses
        {"winner": 2, "plays": ["P2 played [Pirate]"]},    # P0 misses — last miss
    ]
    trick, idx = reflector._find_critical_trick_with_index(pid=0, bid=2, won=1, tricks=tricks)
    assert idx == 2
    assert trick is tricks[2]


def test_find_critical_trick_with_index_no_over_win(reflector):
    """
    Under-bid scenario: bid=2, won=1, only one win for P0.
    The last miss must be returned (the latest trick P0 did not win).
    """
    tricks = [
        {"winner": 0, "plays": ["P0 played [Green 14]"]},
        {"winner": 1, "plays": ["P1 played [Pirate]"]},
        {"winner": 1, "plays": ["P1 played [Skull King]"]},
    ]
    trick, idx = reflector._find_critical_trick_with_index(pid=0, bid=2, won=1, tricks=tricks)
    assert trick is not None
    assert idx >= 1
    # Must be the last trick where P0 did not win — tricks[2]
    assert idx == 2


def test_find_critical_trick_exact_bid_returns_none(reflector):
    """
    When won == bid (success), the over-bid branch is not triggered and the
    under-bid branch (else) searches for misses.  If every trick was won by
    pid there are no misses, so the result must be (None, -1).
    bid=2, won=2 → P0 won every trick → no miss → (None, -1).
    """
    tricks = [
        {"winner": 0, "plays": ["P0 played [Black 11]"]},
        {"winner": 0, "plays": ["P0 played [Pirate]"]},
    ]
    trick, idx = reflector._find_critical_trick_with_index(pid=0, bid=2, won=2, tricks=tricks)
    assert trick is None
    assert idx == -1


# ---------------------------------------------------------------------------
# Tests: _build_situation_query
# ---------------------------------------------------------------------------

def test_build_situation_query_contains_round_info(reflector):
    """
    _build_situation_query must embed the round number, the correct round
    stage label, and the player's bid in the returned string.
    Round 7: not > 7, but > 4 → 'Mid Game'.
    """
    r_data = {
        "starting_hands": {0: ["[Green 7]", "[Pirate]"]},
        "starting_hand_ids": {0: [6, 56]},
        "tricks": [],
        "end_event": None,
    }
    bids = [2, 1, 1, 1]
    won  = [3, 1, 0, 0]

    result = reflector._build_situation_query(
        pid=0, round_num=7, r_data=r_data, bids=bids, won=won
    )

    assert "Round 7" in result
    assert "Mid Game" in result
    assert "Bid 2" in result


def test_build_situation_query_late_game(reflector):
    """
    Round number > 7 must produce the 'Late Game' label.
    """
    r_data = {
        "starting_hands": {0: ["[Skull King]"]},
        "starting_hand_ids": {0: [62]},
        "tricks": [],
        "end_event": None,
    }
    bids = [3, 2, 1, 0]
    won  = [4, 2, 1, 0]

    result = reflector._build_situation_query(
        pid=0, round_num=9, r_data=r_data, bids=bids, won=won
    )

    assert "Late Game" in result


def test_build_situation_query_early_game(reflector):
    """
    Round number <= 4 must produce the 'Early Game' label.
    """
    r_data = {
        "starting_hands": {0: ["[Green 1]"]},
        "starting_hand_ids": {0: [0]},
        "tricks": [],
        "end_event": None,
    }
    bids = [1, 0, 0, 1]
    won  = [1, 0, 0, 2]

    result = reflector._build_situation_query(
        pid=0, round_num=3, r_data=r_data, bids=bids, won=won
    )

    assert "Early Game" in result


# ---------------------------------------------------------------------------
# Tests: _hunger_label (static method)
# ---------------------------------------------------------------------------

def test_hunger_label_full(reflector):
    """
    delta == 0 (bid met, won == bid) → 'FULL'.
    """
    label = SleepCycleReflector._hunger_label(
        bid=2, won=2, round_num=5, total_won=5
    )
    assert label == "FULL"


def test_hunger_label_overboard(reflector):
    """
    delta < 0 (won > bid, player over-scored) → 'OVERBOARD'.
    """
    label = SleepCycleReflector._hunger_label(
        bid=2, won=3, round_num=5, total_won=5
    )
    assert label == "OVERBOARD"


def test_hunger_label_doomed(reflector):
    """
    When tricks_left == 0 but delta > 0, there is no way to recover → 'DOOMED'.
    bid=2, won=0, round_num=5, total_won=5 → tricks_left = 5-5 = 0, delta = 2.
    """
    label = SleepCycleReflector._hunger_label(
        bid=2, won=0, round_num=5, total_won=5
    )
    assert label == "DOOMED"


def test_hunger_label_starving(reflector):
    """
    When delta == tricks_left (must win every remaining trick) → 'STARVING'.
    bid=2, won=0, round_num=5, total_won=3 → tricks_left=2, delta=2 → STARVING.
    """
    label = SleepCycleReflector._hunger_label(
        bid=2, won=0, round_num=5, total_won=3
    )
    assert label == "STARVING"


def test_hunger_label_hungry(reflector):
    """
    When 0 < delta < tricks_left (still achievable but needs more wins) → 'HUNGRY'.
    bid=3, won=1, round_num=6, total_won=3 → tricks_left=3, delta=2 → HUNGRY.
    """
    label = SleepCycleReflector._hunger_label(
        bid=3, won=1, round_num=6, total_won=3
    )
    assert label == "HUNGRY"


def test_hunger_label_bid_hidden(reflector):
    """
    bid == -1 (bid not yet revealed in BIDDING phase) → 'BID_HIDDEN'.
    """
    label = SleepCycleReflector._hunger_label(
        bid=-1, won=0, round_num=5, total_won=3
    )
    assert label == "BID_HIDDEN"
